# fly.toml file generated for resolver on 2023-02-25T18:26:31+01:00

app = "resolver"
kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
