name: flyctl

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flyctl.yml
      - app/**/*

defaults:
  run:
    working-directory: app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
