name: hurl

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"

defaults:
  run:
    working-directory: hurl

jobs:
  hurl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install hurl
        run: |
          cd /usr/local/bin && curl -fsSL https://github.com/Orange-OpenSource/hurl/releases/download/$HURL_VERSION/hurl-$HURL_VERSION-x86_64-linux.tar.gz | sudo tar xz --strip-components 1
          hurl --version
        env:
          HURL_VERSION: 2.0.1

      - name: Run tests
        run: hurl --test *.hurl
