name: smart-contracts

on: [push, pull_request]

env:
  python-version: 3.11.2
  poetry-version: 1.3.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.poetry-version }}
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check formatting with `black`
        run: poetry run black --check .

      - name: Lint with `flake8`
        run: poetry run flake8 . --count --statistics

      - name: Test with `pytest`
        run: poetry run pytest
